### ISSUE TITLE
Add a Nuget Package

### ISSUE THREAD

**Issue by JimBobSquarePants** [AndyButland/UmbracoPersonalisationGroups#3]
It's the new rock n' roll! :guitar: 

This looks great and I want to use it for everything I write.

If the assembly was installable as a Nuget package that would mean I could install it in a project with the following setup and have the website simply inherit the references. [nuPickers](https://github.com/uComponents/nuPickers) works a treat with this so maybe they have code you can borrow. 

```
|__ Site.Logic 
|
|__Site
```

That would be awesome! :smile:

**Comment by AndyButland** [comment]
Thanks James!  I use a similar set-up so that would work for me too - but the package installs a couple of document types and data types too.  Not aware of a way to NuGet those - do you know of anything I've missed there?  

Even if not, a NuGet of the dll and some manual steps for setting up the doc and data types would be good I agree.

**Comment by JimBobSquarePants** [comment]
Yeah, document types are a sticky one. I don't currently know of any way to install them other than by the installer. Maybe it's possible on app start using the content service? 

If not, yeah, if you packaged up the doc/datatypes in a zipfile and passed that as content with instructions to install I would be more than happy with that.

**Comment by JimBobSquarePants** [comment]
Thinking about this again it's certainly possible to create content and data types using the services. Whether it's worth all the typing I don't know.

**Comment by AndyButland** [comment]
Yes, I think probably I'll make a Nuget package, but for people that want to use that, just have the install process be:
 - install from our as an Umbraco package
 - delete the dll from bin
 - install from NuGet

That way all upgrades can be made via NuGet.

As you say could work with the services, but at minimum it means an extra start-up check see if the are already there, so that might be a reason to avoid.

**Comment by JimBobSquarePants** [comment]
Sounds good to me. :+1:

**Comment by AndyButland** [comment]
This has been set up now:

    PM> Install-Package UmbracoPersonalisationGroups
